### PR TITLE
Update tika

### PR DESCRIPTION
**Pull request by eliotjordan**
Updates from upstream

### CODE REVIEW

**Comment by hackartisan** [comment]
@eliotjordan why do we update this way instead of pulling commits directly?

**Comment by eliotjordan** [comment]
@hackartisan We have customized the gem enough and were far behind the upstream enough that syncing was messy (rubocop being the primary cause). The better thing to do here is probably to submit a PR to the upstream gem to allow passing in a config file path.

**Comment by eliotjordan** [comment]
@hackartisan I made an upstream PR: https://github.com/mrcsparker/ruby_tika_app/pull/17

**Comment by hackartisan** [comment]
Awesome!!

**Pull request merged**
